[package]
name = "downloader"
version = "2.0.0"
authors = ["EdJoPaTo <git-commit-with-a-funny-long-email-address-everyone-hates-as-it-is-too-long@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
encoding = "0.2"
itertools = "0.9"
regex = "1.3"
serde_json = "1.0"
url = "2.1"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.reqwest]
version = "0.10"
features = ["blocking"]
