name: Rust

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Log versions'
        run: |
          rustc --version
          cargo --version
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}

      - name: Run clippy
        run: cargo clippy --verbose --all-targets --all-features -- -D warnings -D clippy::pedantic
      - name: Check format
        run: cargo fmt -- --check --verbose

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Log versions'
        run: |
          rustc --version
          cargo --version
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose --locked --all-targets

      - name: Run tests
        run: cargo test --verbose --all-targets

  release:
    name: Release ${{ matrix.triple }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            triple: armv7-unknown-linux-gnueabihf
          - os: ubuntu-latest
            triple: aarch64-unknown-linux-gnu
          - os: macOS-latest
            triple: x86_64-apple-darwin
          - os: windows-latest
            triple: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-release-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo target
        uses: actions/cache@v2
        with:
          path: |
            target
          key: ${{ matrix.triple }}-cargo-release-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.triple }}

      - name: Build release
        uses: actions-rs/cargo@v1
        # TODO: Remove this once it's the default
        env:
           SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
        with:
          command: build
          args: --release --verbose --locked --target ${{ matrix.triple }}
          use-cross: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Upload Artifact (-nix)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: downloader-${{ matrix.triple }}
          path: target/${{ matrix.triple }}/release/downloader
      - name: Upload Artifact (windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: downloader-${{ matrix.triple }}
          path: target/${{ matrix.triple }}/release/downloader.exe

      - name: Inspect root dir
        run: ls

      - name: Pack release (-nix)
        if: runner.os != 'Windows'
        run: |
          rm -f *.tar.gz
          cd target/${{ matrix.triple }}/release
          tar -czvf ../../../downloader-${{ matrix.triple }}.tar.gz downloader
          cd -
      - name: Pack release (windows)
        if: runner.os == 'Windows'
        run: |
          del *.zip
          cd target/${{ matrix.triple }}/release
          7z a ../../../downloader-${{ matrix.triple }}.zip downloader.exe
          cd -

      - name: Inspect root dir
        run: ls

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-downloader-${{ matrix.triple }}
          path: |
            *.zip
            *.tar.gz

      - name: GH Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            *.zip
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
