name: Rust

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --all-targets --all-features -- -D clippy::all -D clippy::pedantic

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt

      - name: Check format
        run: cargo fmt -- --check --verbose

  test:
    name: Test ${{ matrix.rust }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable, nightly]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test --verbose --locked --all-features

  release:
    name: Release ${{ matrix.triple }}
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
            name: downloader-x86_64-unknown-linux-gnu.tar.gz
          - os: ubuntu-latest
            triple: armv7-unknown-linux-gnueabihf
            name: downloader-armv7-unknown-linux-gnueabihf.tar.gz
          - os: ubuntu-latest
            triple: aarch64-unknown-linux-gnu
            name: downloader-aarch64-unknown-linux-gnu.tar.gz
          - os: macOS-latest
            triple: x86_64-apple-darwin
            name: downloader-x86_64-apple-darwin.tar.gz
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
            name: downloader-x86_64-pc-windows-msvc.zip

    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-release-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo target
        uses: actions/cache@v2
        with:
          path: |
            target
          key: ${{ matrix.triple }}-cargo-release-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.triple }}

      - name: Build release
        uses: actions-rs/cargo@v1
        # TODO: Remove this once it's the default
        env:
           SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
        with:
          command: build
          args: --release --verbose --locked --target ${{ matrix.triple }}
          use-cross: ${{ runner.os == 'Linux' }}

      - name: Upload Artifact (-nix)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: downloader-${{ matrix.triple }}
          path: target/${{ matrix.triple }}/release/downloader
      - name: Upload Artifact (windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: downloader-${{ matrix.triple }}
          path: target/${{ matrix.triple }}/release/downloader.exe

      - name: Inspect root dir
        run: ls

      - name: Pack release (-nix)
        if: runner.os != 'Windows'
        run: |
          rm -f *.tar.gz
          cd target/${{ matrix.triple }}/release
          tar -czvf ../../../${{ matrix.name }} downloader
          cd -
      - name: Pack release (windows)
        if: runner.os == 'Windows'
        run: |
          del *.zip
          cd target/${{ matrix.triple }}/release
          7z a ../../../${{ matrix.name }} downloader.exe
          cd -

      - name: Inspect root dir
        run: ls

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-${{ matrix.name }}
          path: ${{ matrix.name }}

      - name: GH Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            *.zip
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
